# Copyright Siemens AG, 2014-2015
# SPDX-License-Identifier:	GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: php

addons:
 - postgresql: "9.3"
cache:
 - apt

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper libglib2.0-dev libmagic-dev libxml2-dev
        libtext-template-perl librpm-dev  rpm libpcre3-dev libssl-dev
        apache2 libapache2-mod-php5 php5-pgsql php-pear php5-cli
        binutils bzip2 cabextract cpio sleuthkit genisoimage poppler-utils
        rpm upx-ucl unrar-free unzip p7zip-full p7zip wget git-core subversion
        libpq-dev
        libboost-regex-dev libboost-program-options-dev
 - sudo apt-get install -qq cppcheck

before_script:
 - cd src/
 - composer install --dev
 - composer self-update
 - cd ..
 - psql -c "CREATE USER fossy WITH PASSWORD 'fossy' CREATEDB;" -U postgres
 - psql -c "create database fossology;" -U postgres

script:
 - set -e
 - make
 - cppcheck -q -isrc/nomos/agent_tests/testdata/NomosTestfiles/ -isrc/testing/dataFiles/ src/
 - phpunit -csrc/phpunit.xml
 - src/vendor/bin/phpcs --standard=src/fossy-ruleset.xml src/lib/php/*/
 - set +e
